// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// edge_use_cuda_backend_internal
bool edge_use_cuda_backend_internal(std::string path);
RcppExport SEXP _edgemodelr_edge_use_cuda_backend_internal(SEXP pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type path(pathSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_use_cuda_backend_internal(path));
    return rcpp_result_gen;
END_RCPP
}
// edge_cuda_backend_path_internal
std::string edge_cuda_backend_path_internal();
RcppExport SEXP _edgemodelr_edge_cuda_backend_path_internal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(edge_cuda_backend_path_internal());
    return rcpp_result_gen;
END_RCPP
}
// edge_cuda_backend_loaded_internal
bool edge_cuda_backend_loaded_internal();
RcppExport SEXP _edgemodelr_edge_cuda_backend_loaded_internal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(edge_cuda_backend_loaded_internal());
    return rcpp_result_gen;
END_RCPP
}
// edge_load_model_internal
SEXP edge_load_model_internal(std::string model_path, int n_ctx, int n_gpu_layers, int n_threads, bool flash_attn, bool embeddings);
RcppExport SEXP _edgemodelr_edge_load_model_internal(SEXP model_pathSEXP, SEXP n_ctxSEXP, SEXP n_gpu_layersSEXP, SEXP n_threadsSEXP, SEXP flash_attnSEXP, SEXP embeddingsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type model_path(model_pathSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctx(n_ctxSEXP);
    Rcpp::traits::input_parameter< int >::type n_gpu_layers(n_gpu_layersSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< bool >::type flash_attn(flash_attnSEXP);
    Rcpp::traits::input_parameter< bool >::type embeddings(embeddingsSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_load_model_internal(model_path, n_ctx, n_gpu_layers, n_threads, flash_attn, embeddings));
    return rcpp_result_gen;
END_RCPP
}
// edge_completion_internal
std::string edge_completion_internal(SEXP model_ptr, std::string prompt, int n_predict, double temperature, double top_p);
RcppExport SEXP _edgemodelr_edge_completion_internal(SEXP model_ptrSEXP, SEXP promptSEXP, SEXP n_predictSEXP, SEXP temperatureSEXP, SEXP top_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type prompt(promptSEXP);
    Rcpp::traits::input_parameter< int >::type n_predict(n_predictSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type top_p(top_pSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_completion_internal(model_ptr, prompt, n_predict, temperature, top_p));
    return rcpp_result_gen;
END_RCPP
}
// edge_free_model_internal
void edge_free_model_internal(SEXP model_ptr);
RcppExport SEXP _edgemodelr_edge_free_model_internal(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    edge_free_model_internal(model_ptr);
    return R_NilValue;
END_RCPP
}
// is_valid_model_internal
bool is_valid_model_internal(SEXP model_ptr);
RcppExport SEXP _edgemodelr_is_valid_model_internal(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(is_valid_model_internal(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// edge_completion_stream_internal
List edge_completion_stream_internal(SEXP model_ptr, std::string prompt, Function callback, int n_predict, double temperature, double top_p);
RcppExport SEXP _edgemodelr_edge_completion_stream_internal(SEXP model_ptrSEXP, SEXP promptSEXP, SEXP callbackSEXP, SEXP n_predictSEXP, SEXP temperatureSEXP, SEXP top_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type prompt(promptSEXP);
    Rcpp::traits::input_parameter< Function >::type callback(callbackSEXP);
    Rcpp::traits::input_parameter< int >::type n_predict(n_predictSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type top_p(top_pSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_completion_stream_internal(model_ptr, prompt, callback, n_predict, temperature, top_p));
    return rcpp_result_gen;
END_RCPP
}
// edge_completion_grammar_internal
std::string edge_completion_grammar_internal(SEXP model_ptr, std::string prompt, std::string grammar_str, std::string grammar_root, int n_predict, double temperature, double top_p);
RcppExport SEXP _edgemodelr_edge_completion_grammar_internal(SEXP model_ptrSEXP, SEXP promptSEXP, SEXP grammar_strSEXP, SEXP grammar_rootSEXP, SEXP n_predictSEXP, SEXP temperatureSEXP, SEXP top_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< std::string >::type prompt(promptSEXP);
    Rcpp::traits::input_parameter< std::string >::type grammar_str(grammar_strSEXP);
    Rcpp::traits::input_parameter< std::string >::type grammar_root(grammar_rootSEXP);
    Rcpp::traits::input_parameter< int >::type n_predict(n_predictSEXP);
    Rcpp::traits::input_parameter< double >::type temperature(temperatureSEXP);
    Rcpp::traits::input_parameter< double >::type top_p(top_pSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_completion_grammar_internal(model_ptr, prompt, grammar_str, grammar_root, n_predict, temperature, top_p));
    return rcpp_result_gen;
END_RCPP
}
// edge_embeddings_internal
NumericMatrix edge_embeddings_internal(SEXP model_ptr, std::vector<std::string> texts, bool normalize);
RcppExport SEXP _edgemodelr_edge_embeddings_internal(SEXP model_ptrSEXP, SEXP textsSEXP, SEXP normalizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< std::vector<std::string> >::type texts(textsSEXP);
    Rcpp::traits::input_parameter< bool >::type normalize(normalizeSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_embeddings_internal(model_ptr, texts, normalize));
    return rcpp_result_gen;
END_RCPP
}
// edge_model_n_embd_internal
int edge_model_n_embd_internal(SEXP model_ptr);
RcppExport SEXP _edgemodelr_edge_model_n_embd_internal(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_model_n_embd_internal(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// edge_chat_apply_template_internal
std::string edge_chat_apply_template_internal(SEXP model_ptr, List messages, bool add_generation_prompt);
RcppExport SEXP _edgemodelr_edge_chat_apply_template_internal(SEXP model_ptrSEXP, SEXP messagesSEXP, SEXP add_generation_promptSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    Rcpp::traits::input_parameter< List >::type messages(messagesSEXP);
    Rcpp::traits::input_parameter< bool >::type add_generation_prompt(add_generation_promptSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_chat_apply_template_internal(model_ptr, messages, add_generation_prompt));
    return rcpp_result_gen;
END_RCPP
}
// edge_model_chat_template_internal
std::string edge_model_chat_template_internal(SEXP model_ptr);
RcppExport SEXP _edgemodelr_edge_model_chat_template_internal(SEXP model_ptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type model_ptr(model_ptrSEXP);
    rcpp_result_gen = Rcpp::wrap(edge_model_chat_template_internal(model_ptr));
    return rcpp_result_gen;
END_RCPP
}
// set_llama_logging
void set_llama_logging(bool enabled);
RcppExport SEXP _edgemodelr_set_llama_logging(SEXP enabledSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type enabled(enabledSEXP);
    set_llama_logging(enabled);
    return R_NilValue;
END_RCPP
}
// edge_simd_info_internal
Rcpp::List edge_simd_info_internal();
RcppExport SEXP _edgemodelr_edge_simd_info_internal() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(edge_simd_info_internal());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_edgemodelr_edge_use_cuda_backend_internal", (DL_FUNC) &_edgemodelr_edge_use_cuda_backend_internal, 1},
    {"_edgemodelr_edge_cuda_backend_path_internal", (DL_FUNC) &_edgemodelr_edge_cuda_backend_path_internal, 0},
    {"_edgemodelr_edge_cuda_backend_loaded_internal", (DL_FUNC) &_edgemodelr_edge_cuda_backend_loaded_internal, 0},
    {"_edgemodelr_edge_load_model_internal", (DL_FUNC) &_edgemodelr_edge_load_model_internal, 6},
    {"_edgemodelr_edge_completion_internal", (DL_FUNC) &_edgemodelr_edge_completion_internal, 5},
    {"_edgemodelr_edge_free_model_internal", (DL_FUNC) &_edgemodelr_edge_free_model_internal, 1},
    {"_edgemodelr_is_valid_model_internal", (DL_FUNC) &_edgemodelr_is_valid_model_internal, 1},
    {"_edgemodelr_edge_completion_stream_internal", (DL_FUNC) &_edgemodelr_edge_completion_stream_internal, 6},
    {"_edgemodelr_edge_completion_grammar_internal", (DL_FUNC) &_edgemodelr_edge_completion_grammar_internal, 7},
    {"_edgemodelr_edge_embeddings_internal", (DL_FUNC) &_edgemodelr_edge_embeddings_internal, 3},
    {"_edgemodelr_edge_model_n_embd_internal", (DL_FUNC) &_edgemodelr_edge_model_n_embd_internal, 1},
    {"_edgemodelr_edge_chat_apply_template_internal", (DL_FUNC) &_edgemodelr_edge_chat_apply_template_internal, 3},
    {"_edgemodelr_edge_model_chat_template_internal", (DL_FUNC) &_edgemodelr_edge_model_chat_template_internal, 1},
    {"_edgemodelr_set_llama_logging", (DL_FUNC) &_edgemodelr_set_llama_logging, 1},
    {"_edgemodelr_edge_simd_info_internal", (DL_FUNC) &_edgemodelr_edge_simd_info_internal, 0},
    {NULL, NULL, 0}
};

void edgemodelr_init(DllInfo *dll);
RcppExport void R_init_edgemodelr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
    edgemodelr_init(dll);
}
