# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

edge_use_cuda_backend_internal <- function(path) {
    .Call(`_edgemodelr_edge_use_cuda_backend_internal`, path)
}

edge_cuda_backend_path_internal <- function() {
    .Call(`_edgemodelr_edge_cuda_backend_path_internal`)
}

edge_cuda_backend_loaded_internal <- function() {
    .Call(`_edgemodelr_edge_cuda_backend_loaded_internal`)
}

edge_load_model_internal <- function(model_path, n_ctx = 2048L, n_gpu_layers = 0L, n_threads = 0L, flash_attn = TRUE, embeddings = FALSE) {
    .Call(`_edgemodelr_edge_load_model_internal`, model_path, n_ctx, n_gpu_layers, n_threads, flash_attn, embeddings)
}

edge_completion_internal <- function(model_ptr, prompt, n_predict = 128L, temperature = 0.8, top_p = 0.95) {
    .Call(`_edgemodelr_edge_completion_internal`, model_ptr, prompt, n_predict, temperature, top_p)
}

edge_free_model_internal <- function(model_ptr) {
    invisible(.Call(`_edgemodelr_edge_free_model_internal`, model_ptr))
}

is_valid_model_internal <- function(model_ptr) {
    .Call(`_edgemodelr_is_valid_model_internal`, model_ptr)
}

edge_completion_stream_internal <- function(model_ptr, prompt, callback, n_predict = 128L, temperature = 0.8, top_p = 0.95) {
    .Call(`_edgemodelr_edge_completion_stream_internal`, model_ptr, prompt, callback, n_predict, temperature, top_p)
}

edge_completion_grammar_internal <- function(model_ptr, prompt, grammar_str, grammar_root, n_predict = 512L, temperature = 0.3, top_p = 0.95) {
    .Call(`_edgemodelr_edge_completion_grammar_internal`, model_ptr, prompt, grammar_str, grammar_root, n_predict, temperature, top_p)
}

edge_embeddings_internal <- function(model_ptr, texts, normalize = TRUE) {
    .Call(`_edgemodelr_edge_embeddings_internal`, model_ptr, texts, normalize)
}

edge_model_n_embd_internal <- function(model_ptr) {
    .Call(`_edgemodelr_edge_model_n_embd_internal`, model_ptr)
}

edge_chat_apply_template_internal <- function(model_ptr, messages, add_generation_prompt = TRUE) {
    .Call(`_edgemodelr_edge_chat_apply_template_internal`, model_ptr, messages, add_generation_prompt)
}

edge_model_chat_template_internal <- function(model_ptr) {
    .Call(`_edgemodelr_edge_model_chat_template_internal`, model_ptr)
}

set_llama_logging <- function(enabled) {
    invisible(.Call(`_edgemodelr_set_llama_logging`, enabled))
}

edge_simd_info_internal <- function() {
    .Call(`_edgemodelr_edge_simd_info_internal`)
}

